"""initial_schema

Revision ID: 81ad433473f7
Revises: 
Create Date: 2026-09-10 17:03:10.810388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ad433473f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'monthly_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subscriptions', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_renewal_date'), 'subscriptions', ['renewal_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.alter_column('support_cases', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('support_cases', 'submitted_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_support_cases_customer_id'), 'support_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_cases_submitted_at'), 'support_cases', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_cases_submitted_at'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_customer_id'), table_name='support_cases')
    op.alter_column('support_cases', 'submitted_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('support_cases', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_renewal_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'monthly_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.alter_column('customers', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
