"""add case_decisions table

Revision ID: 1b25da5b7c32
Revises: 3997f4b7b56b
Create Date: 2026-09-13 23:17:21.514438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b25da5b7c32'
down_revision: Union[str, Sequence[str], None] = '3997f4b7b56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('requires_human_approval', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('routed_to', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_decisions_case_id'), 'case_decisions', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_decisions_case_id'), table_name='case_decisions')
    op.drop_table('case_decisions')
    # ### end Alembic commands ###
